### ISSUE TITLE
Compatibility issue with Easy Villager

### ISSUE THREAD

**Issue by ffuentesm** [Spiderman31807/MC-Modded#1]
The main problem is that Shift Right-Click causes the player to pick up the villager in item mode while opening the Villager Inventory. 
Easy Villager also has a setting where you can keybind a key to pick up the villagers, but the Shift Right-Click is not disabled when that option is bound to a different key. 

So far I was able to access the villager inventory by using Ars Nouveau interact spell, which lets me Shift Right-Click from 10 blocks away, but I do not see that as a viable option. 

Could you make it so that this mod overrides the Shift Right-Click from Easy villages, or that if you Right-Click on a villager with a specific item, like a stick, an emerald, or bread, the menu opens?

**Comment by Spiderman31807** [comment]
i just looked at the source code of the easy villagers mod and it seems there is a Config Option to disable Right Click Pickup.

`if (!Main.CLIENT_CONFIG.enableRightClickPickup.get()) {
            return;
        }`

**Comment by Spiderman31807** [comment]
after a short amount of testing, i can determine that it is not possible to override it, i tried making it the highest priority so my procedure runs first but that didnt work it just opened the inventory then picked it up.. which then closed the inventory.

i also tried forcing the Player to unshift after my code runs so that its code would think the player wasn't shifting when the interaction was made (surprisingly, that did nothing) i mean.. i guess it makes sense since the player already unshifts when an inventory is open, i just thought doing it directly would make it different.

so i can really say to do, is disable it in the config. you just need to go to your "Minecraft Installation Folder -> Config -> easy_villagers-client.toml" and use Notepad, VSCode, or whatever to edit the 'True' to a 'False', if your using CurseForge right click the Modpack click Open Profile, and it'll take you to your Minecraft Installation Folder (for that pack).

There isn't many Conditions or checks for the Easy Villagers mod, thats why im unable to override its interaction, it checks for:
* Entity is a Type of Villager
* Config is Enabled
* Player is Holding Shift (in minecraft shift refers to the button linked to Crouch, not shift itself)
* Villager is Alive & not sleeping

with Shifting not affecting it when changed in my code, that leaves Sleeping that'll look super weird, or dying.. which, well it would kill the villager.

**Comment by ffuentesm** [comment]
Oh, would it be possible to set THIS mod keybind to something changeable? Like how Easy Villagers has a Key bind config. 
I was thinking of maybe using the Middle mouse button for this one instead of Shift Right-Click .

**Comment by Spiderman31807** [comment]
Yes that is possible, shouldn't take long. however i cant have the default bind be middle mouse, since by default that is already binded to pick block, however your free to change it yourself.
